version: "3"

services:
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0
    hostname: master
    environment:
      MASTER: spark://0.0.0.0:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 7077:7077
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
  
  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
    deploy:
      replicas: 4
